trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'awsConnection'
    regionName: 'us-east-1'
    stackName: 'CDK'
    templateSource: 'file'
    templateFile: 'cdk.out/CdkStack.template.json'

